### ISSUE TITLE
Use GitSavvy (free) instead of paid SublimeGit

### ISSUE THREAD

**Issue by alextegelid** [dvcrn/sublimious#3]
I love this layering and preconfiguration idea! One thought though. Would it make sense to use a free package such as [GitSavvy](https://github.com/divmain/GitSavvy) for the git layer?

If you haven't used GitSavvy I highly recommend you to try it. I moved from SublimeGit - even though I paid for SublimeGit - instantly when I discovered GitSavvy, and a lot of development has been done since.

**Comment by dvcrn** [comment]
Great to hear that you like it :)

SublimeGit started open sourcing and doesn't cost money anymore - https://sublimegit.net/buy. Since the latest update you don't need a license either. 

I'll take a look at gitsavvy. If it is better, then sure, why not!

**Comment by alextegelid** [comment]
Oh, I see! That's good news :)

I'll gladly give sublimious a try with or without GitSavvy, but I need more info on how to safely backup and - if needed - restore my current setup. I've grown kind of fond of it :smile:

**Comment by dvcrn** [comment]
For backup, saving your User folder should be enough I think. Just check if there are some sublime-setting files outside of that and save them as well. 

Inside you have your package control config that contains your installed packages. With that you can batch reinstall all of them.

**Comment by dvcrn** [comment]
As of [v0.3.0](https://github.com/dvcrn/sublimious/releases/tag/v0.3.0), GitSavvy replaced SublimeGit as the git layer

**Comment by alextegelid** [comment]
That's great! (Ping @divmain)

**Comment by divmain** [comment]
:) Let me know if you run into any issues!
