### ISSUE TITLE
AceJump Proposal

### ISSUE THREAD

**Issue by skiningham** [dvcrn/sublimious#34]
I use [AceJump](https://github.com/ice9js/ace-jump-sublime) with my personal installation of Sublimious. It's so useful that I think it should be in the core packages. It's a Sublime version of the Avy plugin used in Spacemacs to quickly jump to a specific word, line, or character. Spacemacs: `spc spc`, `spc y`, etc.

Thoughts?

**Comment by dvcrn** [comment]
If you have time, please give this PR a try and let me know what you think

**Comment by dvcrn** [comment]
Released in [v0.8.0](https://github.com/dvcrn/sublimious/releases/tag/v0.8.0)
