### ISSUE TITLE
How to change key bindings?

### ISSUE THREAD

**Issue by Kyran-C** [dvcrn/sublimious#36]
I don't see any mention on how to bind different keys. The Default.sublime_keymap file says not to modify it and use .sublimious instead, but nothing I've tried has worked. What section should the key binds go in, and what is the proper syntax?

**Comment by dvcrn** [comment]
Apologies, this project hasn't been updated for a quite a while so things like this never got around to getting implemented.

In short, sublimious is currently only to pull keymaps from layers so you'll have to define them there and not inside the `.sublimious` file. Something like [here](https://github.com/dvcrn/sublimious/blob/master/layers/core/layer.py#L126).

**Comment by Kyran-C** [comment]
Okay, thanks for the reply. I thought they might have been hardcoded in but I got thrown off by the auto-generated message in the keymap file saying to define them in .sublimious instead. I'll just hardcode them in, or maybe write a new layer that reads user keybinds from the .sublimious file. My python skills are pretty rough but if I get something production worthy, I'll send you a pull request.
