### ISSUE TITLE
Add external repositories to .sublimious file

### ISSUE THREAD

**Issue by BamBalaam** [dvcrn/sublimious#39]
When installing packages on Sublime Text, these are sometimes only present in external repositories.

It should be possible to add a list of external repositories in the .sublimious file, that would be added to Package Control before going through the installation of the "additional packages".

(I can gladly have a look at how to tackle this issue myself if you could give me some pointers, as I don't know the existing code base as well as you do)

**Comment by dvcrn** [comment]
That would definitely be useful. 

To implement this you would have to see where package control saves that information and then manually write to that file. SublimeText should automatically reload that file once it's written and the repositories available
