### ISSUE TITLE
What to do after install?

### ISSUE THREAD

**Issue by lmartins** [dvcrn/sublimious#4]
Im curious about this package, as I do tend to use the Vim bindings in Sublime and Atom. However, after installing this package on both my machines nothing happens. Is there any additional step? Does the fact that Im using vim bindings already make any difference?

Thank you.

**Comment by dvcrn** [comment]
I assume you installed it through package control? Package control is not officially supported yet. I just released a hotfix to pc though which should get rid of most problems. If you upgrade through package control, make sure that `.sublimious` in your home directory does either not exist or is a file. The previous version created a folder which was not correct.

The normal behavior after installation is that you should get a popup that explains you what you have to do. 
![screen shot 2015-09-20 at 9 35 17 am](https://cloud.githubusercontent.com/assets/688326/9978670/f7a8e932-5f7a-11e5-8f6d-e5eac3b6939f.png)

Once you activate the extension it will start collecting layers and setting configs accordingly
