### ISSUE TITLE
This plugin just fucked up my whole sublime text

### ISSUE THREAD

**Issue by nopmop** [dvcrn/sublimious#41]
![image](https://user-images.githubusercontent.com/309981/39063513-9cc74f34-44cb-11e8-8b1e-15e1f541daf0.png)

Thank you! 

How can you make software this way...wiping the whole config & reinstalling all the plugins, that's madness :unamused:

**Comment by BamBalaam** [comment]
From the README:

`Be warned! Sublimious is a complete configuration system and will nuke your existing configuration. Make sure to backup your configs before trying sublimious!`

From the .sublimious file you had to modify:

`Change the following line to True to activate sublimious
By changing it to true, you are aware that this will wipe your configuration.
Please make sure that you have a backup in place! (eg backup User/)
I mean, seriously. This will delete ALL your sublime setting files`

You had to modify a variable called `nuke_everything`...

HOW is it a surprise that it wiped your configuration?

**Comment by nopmop** [comment]
Mad cut & paste skillz @BamBalaam  :trophy:  ...exactly what this software probably is about.

Why don't you just devise another way of installing this crap instead? A "wipe everything" strategy is simply **absurd** to install any software. I can't even begin to list all the consequences (plugins having disappeared in the meantime, reindexing killing the CPU for large codebases, themes conflicting and destroying the UI, etc. etc.).

> HOW is it a surprise that it wiped your configuration?

I'll pray you get fingers & knucles arthritis after this.
Seriously.

**Comment by BamBalaam** [comment]
Your aggressive stance and replies are extremely strange. 

This piece of **free and open-source software** tells you up front **what it does**, and **how** it does it. 

If you believe that it is a bad process, there are several possible solutions, which are the same for any open-source software:

- Suggest a way to fix it in a constructive manner, if you have one, but don't have the time to invest to program it. The maintainer of the project will evaluate it and maybe invest time in that approach.
- Publish a pull request if you have the time to try and program your solution.
- Don't use the software if you feel like it is buggy/doesn't work/isn't achieving its goal.

Creating an issue like the one you did is not constructive. As is wishing people you don't even know to suffer from diseases.

**Comment by nopmop** [comment]
@BamBalaam you learned very well from those European bureaucrats in Brussels, I see. Excellent again :trophy: 

With people like you in the contirbutors the most I'd make is a PR to the README to let users know what can really happen to them.

Thanks.

**Comment by BamBalaam** [comment]
I'll stop replying after this message. Ad hominem argumentative strategy is petty. You know nothing about me, so those attacks are childish at best. 

The README file *already* includes a warning about what happens when using this software, as does the config file. If you feel that they aren't explicit enough, you are more than welcome to update them and submit a PR. I'm only a contributor, the final decision on whether to accept it or not is the project owner's.

Bye bye.

:trophy:

**Comment by nopmop** [comment]
Sure, I'll stop replying too...

...after pointing out that your participation gave no contribution too :trophy: 

Spare me your comments next time.

Cheers.
